### ISSUE TITLE
Question about Laplace learning with normalization

### ISSUE THREAD

**Issue by choltz95** [jwcalder/GraphLearning#3]
Hi, thanks so much for your work on this. Graph Learning has been really helpful for my projects. I am curious about extending Laplace learning with quadratic constraints. This isn't really a question about the software, but I'm wondering if we could address degeneracy at low label rates by solving an "idealized" semi-supervised problem analogous to Laplacian Eigenmaps?

Something similar to Laplace learning with additional constraints to normalize X:

$$
\begin{aligned}
&\min_{X\in \mathbb{R}^{n\times k}} tr(X^\top L X) && \text{(cut objective)} \\
&\text{s.t. } X_i = y_i \text{ } \forall \text{ labels } i, && \text{(label constraints)} \\ 
&v^\top X = 0,\:\: X^\top D X = I && \text{(cut constraints)}
\end{aligned}
$$

One approximation could just involve taking the eigenvectors of the Laplacian and finding an orthogonal transform (using procrustes / svd) to align the predictions of labeled nodes with their actual labels. I guess this is similar in principle to finding a classifier in the space spanned by the leading eigenvectors of the Laplacian which does reasonably with few labels, but it's not necessarily a good solution to the problem I wrote.

**Comment by jwcalder** [comment]
Hi Chester,

Thanks for your question. Unfortunately you can't add additional constraints in Laplace learning. The solution is already unique with (cut objective) and (label constraints). Adding (cut constraints) will result, in general, in non-existence of a solution. 

The best method we have for low label rates is Poisson Reweighted Laplace learning. It's a little different than our Poisson learning algorithm, and uniformly better (though not always by much).  We used it in a [recent paper](https://arxiv.org/abs/2210.15786) and will be describing it in detail in a forthcoming paper. You can try it out if you like:

```model = gl.ssl.laplace(W, reweighting='poisson')```

**Comment by choltz95** [comment]
Hi Professor- appreciate your response. Thanks as well for the paper you linked. I'll take some time to think about the first part of your note.

The reason I asked is because Laplace learning + quadratic constraints can be re-written to look like a trust-region subproblem over the unlabeled vertices of the graph and the unlabeled sub-matrix of $L$; ( $X'$ , $L'$):

$$
\begin{aligned}
&\min_{X'\in \mathbb{R}^{n'\times k}} tr((X')^\top L' X') + tr(B^\top X')  && \text{(cut objective + label constraints)} \\
&(X')^\top X' = C && \text{(cut constraints)}
\end{aligned}
$$

The existence of a solution just corresponds to some optimality conditions on this problem and assumptions about $C$. And I was reading about some principled methods for finding approximate solutions that are also robust to degenerate instances of this problem (so-called "hard" cases e.g. when ||B|| is close to zero / few unlabeled vertices & there could be none or many solutions). I was mainly curious to see if there was some novelty with adding certain kinds of constraints (or if it's likely not a good direction) or if some of these trs methods could be applied to get empirical gains or imply something interesting. Interestingly, the approximate algorithm I mentioned does do pretty well compared with vanilla Laplace learning & Poisson learning.

**Comment by jwcalder** [comment]
The problem you write down is essentially Poisson learning if you pose it over all the nodes and B encodes the labels (though our constraint is mean-zero in place of your cut constraint). You should read our [paper](https://arxiv.org/abs/2006.11184) carefully. In fact, we also noticed that if you impose some constraints on Laplace learning, like centering so the mean is zero, then you can fix a lot of the issues at low label rates. We describe shifting the solution of Laplace learning to have mean value zero in our Poisson learning paper. The results are incredibly better (from 16% up to around 90%) and similar to Poisson learning. Of course it doesn't make sense to impose the mean zero constraint on Laplace learning, as you lose the label constraint, so this is exactly what motivated Poisson learning for us, as a principled way to enforce the mean zero constraint. Poisson learning has a unique solution and a variational (and random walk) interpretation, while shifted Laplace learning has none of these.

I'm not really sure I follow your discussion about there being no solutions or many solutions and finding approximate solutions that are robust to degeneracies. I would prefer to find a better equation that does not have the degeneracies, since it would not be clear what your method is doing if the optimization algorithm is finding approximate solutions that are somehow better than the true solution of the problem. If this is really the case, that some approximate solution is more robust, then I would advise you to try and understand a better way of interpreting the approximate solution; maybe it solves another, better posed, equation that does not have the degeneracy. This is what we did in Poisson learning.

Usually in graph learning we pose a problem (a PDE or variational problem on a graph) and it is important to pose one that has a unique solution. The optimization procedure is secondary, and you should simply choose the most efficient method to solve the problem, but I do not think it should not play a role in selecting a solution.

**Comment by choltz95** [comment]
Hi Professor- Thanks for your insight. I really appreciate your time and your suggestions. I'll close this issue for now and spend some time to carefully review your work.
