### ISSUE TITLE
ssl_accuracy bug & poisson learning

### ISSUE THREAD

**Issue by choltz95** [jwcalder/GraphLearning#5]
I believe the current definition of [ssl_accuracy](https://github.com/jwcalder/GraphLearning/blob/master/graphlearning/ssl.py#L1778) assumes that predictions interpolate the labels at the training samples. For those ssl algorithms that may not interpolate the labels at training points (e.g. poisson learning) without some postprocessing, the function may not return the correct accuracy on the unlabeled vertices. The gap could be particularly large when the number of labels is large.

Here is one testcase to show the issue:
https://colab.research.google.com/drive/1mceiaOMsqdT0kDvFzeAaBe_PfNFoofNh?usp=sharing

**Comment by jwcalder** [comment]
Hi Chester,

Thanks for noticing this! You are correct that ssl_accuracy assumes the labels are correct at labeled nodes, and will give an incorrect and lower accuracy score when some  training points are labeled incorrectly.

However, it's not as bad as you showed in your notebook (100% vs 96.89%). You have a bug in your correct accuracy function; you are comparing pred_labels to pred_labels! (see code below)

`return 100*np.maximum(np.sum(pred_labels[I]==pred_labels[I]),0)/I.sum()`

If you  change one of those to true_labels, you'll get 97.31%, so a 0.42% difference. 

However, your correct_accuracy function includes both training and testing data. I prefer not to test the algorithm on the training data, since the algorithm is given the labels for these data points. That was the spirit of ssl_accuracy; to remove the training data from the computation. If you do this in your notebook, the code is 

```
test_mask = np.ones(len(pred_labels),dtype=bool)
test_mask[train_ind] = False
print(np.mean(pred_labels[test_mask]==labels[test_mask]))
```

which produces 97.17% accuracy. So the difference is quite small (now 0.28%). But it is really important to get things right, so thanks very much for bringing this to my attention. I will update the package to fix this bug, probably by asking that ssl_accuracy takes the training indices as an input, so they can be removed like in my code above. This is used in some other parts of the package so it may take me a bit of time to fix it. 

Best,
Jeff

**Comment by choltz95** [comment]
Got it - thanks for the clarification.

**Comment by jwcalder** [comment]
I've fixed the bug now, ssl_accuracy now requires the user to pass in the training indices, not just the number of labels. The training points are removed before computing accuracy. It will give a warning if you try and use it the old way. Let me know if you run into any other issues. I'll close this issue now.
